server:
  port: 8088

spring:
  messages:
    basename: messages
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

management:
  endpoints:
    web:
      exposure:
        include: "*"

jpa:
  show-sql:true

h2:
  console:
    enabled:true
